### ISSUE TITLE
PHP 7.4 throws deprecation notice

### ISSUE THREAD

**Issue by michaelsavchuk** [CurtisL/wp-cli-project#14]
When running WP CLI 2.4.0 on PHP 7.4 with the project command installed I get this error:

```
PHP Deprecated:  implode(): Passing glue string after array is deprecated. Swap the parameters in /Users/.../.wp-cli/packages/vendor/sole-graphics/wp-cli-project/project-command.php on line 27

Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /Users/.../.wp-cli/packages/vendor/sole-graphics/wp-cli-project/project-command.php on line 27
```

According to the [PHP 7.4 deprecation docs](https://www.php.net/manual/en/migration74.deprecated.php):
> Passing parameters to implode() in reverse order is deprecated, use `implode($glue, $parts)` instead of `implode($parts, $glue)`.

**Comment by CurtisL** [comment]
Good Catch, gotta love PHP.
